### ISSUE TITLE
Really Simple SSL with Cloudflare

### ISSUE THREAD

**Issue by ShaoboZhangProduction** [rlankhorst/really-simple-ssl#156]
I checked the document in the website <https://really-simple-ssl.com/knowledge-base/ssl-cloudflare-really-simple-ssl/>. However, it didn't explain if I could use the Couldflare instead of the Really simple SSL. Should I active both of them?

**Comment by mwolters90** [comment]
You can have both Cloudflare and Really Simple SSL active at the same time. Really Simple SSL will update internal links and links to external resources to https://, that is not something Cloudflare will do.
