### ISSUE TITLE
Site hosted on AWS - https not working on instance update.

### ISSUE THREAD

**Issue by robcifre** [rlankhorst/really-simple-ssl#176]
So I have a site on wordpress, and when I upload a new update to the instance on aws the site pretty much dies with too many redirects. So I need to go into the database, remove the https and convert it back to normal http. Then I have to login to the site, go to the plugins page, refresh the plugin page and then the site works.

**Comment by robcifre** [comment]
Thank you very much! The wp-config was getting written to after the page was on the server. Checking the wp-config I noticed your plugin writes to it... i added this to the package before uploading to AWS and now everytime i upload really simple ssl works out of the box.

Code:
`//Begin Really Simple SSL Load balancing fix
if ((isset($_ENV["HTTPS"]) && ("on" == $_ENV["HTTPS"]))
|| (isset($_SERVER["HTTP_X_FORWARDED_SSL"]) && (strpos($_SERVER["HTTP_X_FORWARDED_SSL"], "1") !== false))
|| (isset($_SERVER["HTTP_X_FORWARDED_SSL"]) && (strpos($_SERVER["HTTP_X_FORWARDED_SSL"], "on") !== false))
|| (isset($_SERVER["HTTP_CF_VISITOR"]) && (strpos($_SERVER["HTTP_CF_VISITOR"], "https") !== false))
|| (isset($_SERVER["HTTP_CLOUDFRONT_FORWARDED_PROTO"]) && (strpos($_SERVER["HTTP_CLOUDFRONT_FORWARDED_PROTO"], "https") !== false))
|| (isset($_SERVER["HTTP_X_FORWARDED_PROTO"]) && (strpos($_SERVER["HTTP_X_FORWARDED_PROTO"], "https") !== false))
|| (isset($_SERVER["HTTP_X_PROTO"]) && (strpos($_SERVER["HTTP_X_PROTO"], "SSL") !== false))
) {
$_SERVER["HTTPS"] = "on";
}`

**Comment by rlankhorst** [comment]
Glad to hear it's resolved!
