### ISSUE TITLE
URL without slash loses parameters on redirect

### ISSUE THREAD

**Issue by jfurneaux** [rlankhorst/really-simple-ssl#18]
This URL: http://hive.com/slack?utm_campaign=Linkedin&utm_source=linkedin&utm_medium=paidsocial is converted to https://hive.com/slack

http://hive.com/slack/?utm_campaign=Linkedin&utm_source=linkedin&utm_medium=paidsocial works correctly.

Hope that makes sense?

**Comment by rlankhorst** [comment]
Hi, I'm not sure how this is related to Really Simple SSL?
