### ISSUE TITLE
Enhancement Request: Avoid multiple page redirects 

### ISSUE THREAD

**Issue by garretthyder** [rlankhorst/really-simple-ssl#270]
Hello,

I recently found with Really Simple SSL and a setup using www.domain.com that you end up with the multiple page redirect issue as the RSSSL htaccess redirects to HTTP_HOST and then WP will redirect to WWW if you started on the naked domain.
<img width="743" alt="Screen Shot 2020-05-19 at 8 12 56 PM" src="https://user-images.githubusercontent.com/8726005/82401039-97c8e800-9a0d-11ea-92fd-2d020f189dba.png">

To fix this I updated the htaccess record to swap HTTP_HOST for my www version of the domain. It would be nice if the plugin took into account the site URL and used it instead of HTTP_HOST to avoid the double redirect.

Hope that makes sense,
Always loved the plugin.
Cheers

**Comment by rlankhorst** [comment]
Hi @garretthyder, 

Thanks for the feedback. This redirect is actually a best practice redirect, as for SSL redirects it is considered most secure to pass through both domain variations. If a HSTS header is set, it will get set on both domains. If in your example the non www domain would be bypassed, the HSTS header would not get set on the non www domain, allowing man in the middle attacks on the non www domain for such users. 

For more details, check this article:
Avoid landing page redirects, redirecting www to non www or vice versa

Let me know if you have any questions!

**Comment by garretthyder** [comment]
Thanks @rlankhorst, the article link didn't make it can you repost it please.

**Comment by rlankhorst** [comment]
@garretthyder Sorry!
https://really-simple-ssl.com/knowledge-base/avoid-landing-page-redirects/

**Comment by garretthyder** [comment]
Thanks for the reference and information @rlankhorst closing out this ticket.
