### ISSUE TITLE
Buffer functions can cause problems with chunked file downloads

### ISSUE THREAD

**Issue by cklosowski** [rlankhorst/really-simple-ssl#30]
At EDD we had a customer running the plugin but as soon as it was activated, existing file downloads started failing. We narrowed it down to these two hooks:
`add_action("init", array($this, "start_buffer"));`
`add_action("shutdown", array($this, "end_buffer"));`

We were originally going to just remove the actions, but they are within a class that is inaccessible to 3rd party plugins.

I'm going to work up a PR that should help that.

**Comment by rlankhorst** [comment]
Thanks for the feedback. 

This is the mixed content fixer, you could deactivate it entirely by disabling the option in settings/ssl. But if you would want to deactivate it conditionally, I could add a hook. 

But if this is a generic issue, I'd like to fix it entirely. I've had a report that this also happens with Woocommerce downloads. The best would be if the plugin can recognize when a download is being requested. I'll think about this, but any input is welcome of course. 

I use EDD too, but do not have this issue, which means that this is only occurring when an existing site with EDD moves to SSL?

**Comment by cklosowski** [comment]
@rlankhorst Yep thats the case. When an existing site moves over. I'm working up the PR as we speak, will get it done, test it out, and then submit if you are ok with that. Happy to help out.

**Comment by cklosowski** [comment]
Our goal was to re-factor the main plugin file so that the classes that load up the hooks can be accessed. Right now since they aren't accessible, a `remove_action` isn't possible because the instance of the mixed content fixer isn't available to other plugins.

**Comment by rlankhorst** [comment]
Ok, thanks, I'll await your PR.

**Comment by cklosowski** [comment]
Ok, I had to rework quite a bit, but this should clean up access and remove calls to global variables and makes the main plugin a singleton, to prevent multiple instantiations.

to test it, I simply made an mu-plugin that does this:
```
<?php
function maybe_remove_mixed_content_filter() {
	if ( class_exists( 'RLRSSSL' ) ) {
		remove_action( "init", array( RSSSL()->rsssl_mixed_content_fixer, "start_buffer" ) );
		remove_action( "shutdown", array( RSSSL()->rsssl_mixed_content_fixer, "end_buffer" ) );
	}
}
add_action( 'plugins_loaded', 'maybe_remove_mixed_content_filter', 999, 1 );
```

**Comment by rlankhorst** [comment]
Ok thanks. Do you have a way to check if it's a file download to apply this conditionally?

**Comment by rlankhorst** [comment]
Looks like you did a lot of work, thanks.

**Comment by cklosowski** [comment]
Hey @rlankhorst sorry missed your last comment.

I think our plan is to run a check like so:
`did_action( 'edd_process_verified_download' )`

That will tell us that we've started the file download process, then we can remove the hooks if we detect them.

**Comment by cklosowski** [comment]
My updated sample:
```
<?php
function maybe_remove_mixed_content_filter() {
	if ( class_exists( 'RLRSSSL' ) && did_action( 'edd_process_verified_download' ) ) {
		remove_action( "init", array( RSSSL()->rsssl_mixed_content_fixer, "start_buffer" ) );
		remove_action( "shutdown", array( RSSSL()->rsssl_mixed_content_fixer, "end_buffer" ) );
	}
}
add_action( 'plugins_loaded', 'maybe_remove_mixed_content_filter', 999 );
```

**Comment by rlankhorst** [comment]
Great, thanks for your input :)

**Comment by rlankhorst** [comment]
Just one more thing, maybe you have a better suggestion for this: I'm struggling a bit with the compatibility with an add-on: I'm thinking the only way to handle that would be to check for the version of the add-on, and depending on that, include the old code or the new code. Which is not very elegant. But otherwise the plugin would break if the free version is updated first.

**Comment by cklosowski** [comment]
Ah, the extensions are all accessing the global variables? Let me see if I can get those to work, give me just a few.

**Comment by cklosowski** [comment]
@rlankhorst see if that fixes the backwards compatibility for you.

This should allow you to release the free core, with the updates, and then slowly work all your addons to support the new direct access while still being able to access the old globals if they don't exist.

**Comment by rlankhorst** [comment]
Yes, this works perfectly. Thanks for all your input. It's merged.

**Comment by rlankhorst** [comment]
@cklosowski As I 've encountered a similar issue with JetPack, I've changed the mixed content fixer hook from init to template_redirect, this should prevent the mixed content fixer from firing on requests which are not webpage.
