### ISSUE TITLE
issuing SSL certs through LetsEncrypt

### ISSUE THREAD

**Issue by chris18890** [rlankhorst/really-simple-ssl#68]
In the setup instructions, you say

"Get an SSL certificate (can't do that for you, sorry)"

I wonder if it's possible to use the LetsEncrypt API to do this?

**Comment by rlankhorst** [comment]
That would be possible, but there's already a solution for this:
https://wordpress.org/plugins/wp-encrypt/
It is not really plug and play though: users need to be able to access and modify the server configuration, and not all hosting companies support this. 

I think it's best to keep these separated, as only part of the WordPress users would be able to use these features. Let me know what you think!

**Comment by chris18890** [comment]
Sounds good! I already use the official LE client via SSH for my servers, but will pass this on to other web devs who use your plugin :)
