### ISSUE TITLE
 Call to a member function flush_rules() on null

### ISSUE THREAD

**Issue by dansleboby** [rlankhorst/really-simple-ssl#86]
Hello,
I got this error when I try to activate:

Fatal error: Call to a member function flush_rules() on null in /home/imprimerie/public_html/wp-includes/rewrite.php on line 273

**Comment by rlankhorst** [comment]
Hi, thanks for your feedback. Did you try disabling the checkbox "flush rewrite rules" next to the activate button? This usually fixes the error. 

This sometimes happens in specific configurations with other plugins and can't be reproduced consistently. 
If you have a solution which flushes the rewrite rules without creating the conflict, you can create a pull request. Community patches are much appreciated :)

**Comment by rlankhorst** [comment]
We have found a solution for this by delaying the flush until one minute after activation. This fix is included in the current git master, and will be released in version 3.0.3
