### ISSUE TITLE
Enable Https on specific subdomains [wpml]

### ISSUE THREAD

**Issue by shakee93** [rlankhorst/really-simple-ssl#99]
is there anyway i can enable https on a single subdomain ?

i have wpml installed on the instance. the language translated sites are on `de.example.com`, `no.example.com`  i need to enable https only on `no.example.com`. is there any possibilities i can achieve this using this plugin ?

Thanks in advance..

**Comment by rlankhorst** [comment]
Is this a multisite setup? If you are using multisite, this is built in. You can choose to enable per site.

**Comment by rlankhorst** [comment]
For that purpose, I would recommend to use these  instructions:
https://really-simple-ssl.com/knowledge-base/preventing-subdomains-add-domains-getting-forced-https/

**Comment by shakee93** [comment]
thanks for that article. i can actually force the sub domains to https via cloudflare page rules. i am worried about the mixed content. is there any hooks or anything i can do to achieve this ?

the reason i need to update only the subdomain is the traffic and google ranking.

**Comment by rlankhorst** [comment]
You could use safe mode to activate only the mixed content fixer:
https://really-simple-ssl.com/knowledge-base/using-safe-mode/

**Comment by shakee93** [comment]
Hey sorry for the delayed response.

would that be able to activate that on a single domain ?

**Comment by rlankhorst** [comment]
Yes, that can be used both on single and on multisite.

**Comment by shakee93** [comment]
Thanks. i have managed to achieve this via your mixed content class.
